[package]
name = "music"
version = "0.1.0"
authors = ["axel paulander <axel.paulander@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.14"
nom = "7.0.0"
fraction = "0.9.0"
